name: fit_tracker
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  qr_flutter: ^4.0.0

  image_picker: ^0.8.7+3
  
  cupertino_icons: ^1.0.8
  file_picker: ^8.1.2
  google_fonts: ^6.0.0
  flutter_svg: ^2.0.10+1
  sqflite_common_ffi: ^2.3.4
  sqflite: ^2.4.0
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0



flutter:
  uses-material-design: true

  assets:
    - assets/images/  # Inclui todos os assets da pasta images

# Para usar a fonte Black Han Sans com google_fonts
# No código Dart, use:
# GoogleFonts.blackHanSans()
